context:
  version: "6.15.0"

package:
  name: prisma-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@prisma/language-server/-/language-server-${{ version }}.tgz
  sha256: 5f065db5a8cfef003dc7f0098f30b576f43d751d7bfcac463df9bad852ac567e

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - prisma-language-server --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Implements language-server-protocol for Prisma
  homepage: https://github.com/prisma/language-tools
  repository: https://github.com/prisma/language-tools

extra:
  recipe-maintainers:
    - danielnachun
