context:
  version: "31.5.0"

package:
  name: prisma-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@prisma/language-server/-/language-server-${{ version }}.tgz
  sha256: 62fef2860269bf8d4e90477ec8abeed282cbe065d1fcada1126dfdbbe74c56b2

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - prisma-language-server --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Implements language-server-protocol for Prisma
  homepage: https://github.com/prisma/language-tools
  repository: https://github.com/prisma/language-tools

extra:
  recipe-maintainers:
    - danielnachun
