context:
  version: "31.7.0"

package:
  name: prisma-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@prisma/language-server/-/language-server-${{ version }}.tgz
  sha256: 9a6d950cdcfcbf9b4d2b9ca53ad9e8337ce0b2e4ff6a3e2c0fee6ae4b5af2860

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - prisma-language-server --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Implements language-server-protocol for Prisma
  homepage: https://github.com/prisma/language-tools
  repository: https://github.com/prisma/language-tools

extra:
  recipe-maintainers:
    - danielnachun
