context:
  version: "31.12.2"

package:
  name: prisma-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@prisma/language-server/-/language-server-${{ version }}.tgz
  sha256: c6a2a1e571fd0582c06f32e0a30094499bc596d391b7f7903a1102693d730921

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - prisma-language-server --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Implements language-server-protocol for Prisma
  homepage: https://github.com/prisma/language-tools
  repository: https://github.com/prisma/language-tools

extra:
  recipe-maintainers:
    - danielnachun
