context:
  version: "31.11.0"

package:
  name: prisma-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@prisma/language-server/-/language-server-${{ version }}.tgz
  sha256: 242768e21ebcc33b9fcb139f8ed05160821ddaf372ff6ecf10e3fbf5d80e7651

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - prisma-language-server --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Implements language-server-protocol for Prisma
  homepage: https://github.com/prisma/language-tools
  repository: https://github.com/prisma/language-tools

extra:
  recipe-maintainers:
    - danielnachun
